### set-complete
POST {{host}}/api/set-complete
Content-Type: application/json

{
  "id": 1637,
  "state": false
}

### set-printing
POST {{host}}/api/set-printing
Content-Type: application/json

{
  "id": 1637,
  "state": true
}

### list-queue
GET {{host}}/api/list-queue?withParentComplete=true&withChildrenComplete=true
Content-Type: application/json
