### Send POST request with json body
POST {{host}}/api/list
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send GET request
GET {{host}}/api/list
Content-Type: application/json

### exec
GET {{host}}/commands/printor2/exec
Content-Type: application/json
