name: Deploy prod

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy_go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: "make build"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            IdentitiesOnly=yes
            StrictHostKeyChecking no
            HostKeyAlgorithms +ssh-rsa,ssh-ed25519
            PubkeyAcceptedKeyTypes +ssh-rsa,ssh-ed25519
            ServerAliveInterval 600
            TCPKeepAlive yes
            IPQoS=throughput
          END
        env:
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.VPS_IP }}

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          PG_HOST=localhost
          PG_PORT=5432" > .env
      
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          scp  3dfactory prod:/home/deployer/www/factory-deploy/
          ssh  prod "cd /home/deployer/www/factory-deploy/"
          ssh  prod "make stop"
          ssh  prod "make goose-up"
          ssh  prod "make start"
