name: Deploy prod

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy_go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker compose -f deploy/docker-compose.yaml build
          docker tag 3d-factory:latest ${{ secrets.DOCKER_USERNAME }}/3d-factory:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/3d-factory:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            IdentitiesOnly=yes
            StrictHostKeyChecking no
            HostKeyAlgorithms +ssh-rsa,ssh-ed25519
            PubkeyAcceptedKeyTypes +ssh-rsa,ssh-ed25519
          END
        env:
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.VPS_IP }}

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          PG_HOST=localhost
          PG_PORT=5432" > .env
      
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          scp  .env prod:/www/factory-deploy/
          scp  docker-compose.yaml prod:/www/factory-deploy/
          scp  config/values.yaml prod:/www/factory-deploy/config/values.yaml
          ssh  prod "docker compose -f /www/factory-deploy/docker-compose.yaml pull"
          ssh  prod "docker compose --env-file /www/factory-deploy/.env -f /www/factory-deploy/docker-compose.yaml run --rm migrations"
          ssh  prod "docker compose --env-file /www/factory-deploy/.env -f /www/factory-deploy/docker-compose.yaml up -d --build"
