name: Deploy prod

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker-compose -f /deploy/docker-compose.yaml build
          docker tag 3d-factory:latest ${{ secrets.DOCKER_USERNAME }}/3d-factory:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/3d-factory:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no .env $VPS_USER@$VPS_IP:/www/factory-deploy/
          scp -o StrictHostKeyChecking=no docker-compose.yml $VPS_USER@$VPS_IP:/www/factory-deploy/
          scp -o StrictHostKeyChecking=no config/values.yaml $VPS_USER@$VPS_IP:/www/factory-deploy/config/values.yaml
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "docker-compose -f /www/factory-deploy/docker-compose.yml pull"
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "docker-compose --env-file /www/factory-deploy/.env -f /www/factory-deploy/docker-compose.yml run --rm migrations"
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "docker-compose --env-file /www/factory-deploy/.env -f /www/factory-deploy/docker-compose.yml up -d --build"
