name: Deploy prod

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker compose -f deploy/docker-compose.yaml build
          docker tag 3d-factory:latest ${{ secrets.DOCKER_USERNAME }}/3d-factory:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/3d-factory:latest

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ secrets.VPS_IP }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/id_ed25519
          echo -e "Host *\n  HostkeyAlgorithms +ssh-rsa\n  PubkeyAcceptedKeyTypes +ssh-rsa" >> /home/runner/.ssh/config

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -i /home/runner/.ssh/id_ed25519 .env $VPS_USER@$VPS_IP:/www/factory-deploy/
          scp -i /home/runner/.ssh/id_ed25519 docker-compose.yaml $VPS_USER@$VPS_IP:/www/factory-deploy/
          scp -i /home/runner/.ssh/id_ed25519 config/values.yaml $VPS_USER@$VPS_IP:/www/factory-deploy/config/values.yaml
          ssh -i /home/runner/.ssh/id_ed25519 $VPS_USER@$VPS_IP "docker compose -f /www/factory-deploy/docker-compose.yaml pull"
          ssh -i /home/runner/.ssh/id_ed25519 $VPS_USER@$VPS_IP "docker compose --env-file /www/factory-deploy/.env -f /www/factory-deploy/docker-compose.yaml run --rm migrations"
          ssh -i /home/runner/.ssh/id_ed25519 $VPS_USER@$VPS_IP "docker compose --env-file /www/factory-deploy/.env -f /www/factory-deploy/docker-compose.yaml up -d --build"
